### ISSUE TITLE
Example use needs to call the function?

### ISSUE THREAD

**Issue by goggledefogger** [substack/get-browser-rtc#1]
I'm wanting to use this lib to check for webrtc support, and your readme says all I have to do is check for true/false of require('get-browser-rtc'). But I don't think that's correct, that require statement returns a function, so it will be true every time. I believe the correct call would be:
`var isSupported = !!require('get-browser-rtc')()`

notice the extra parens at the end, which then calls the function, and evaluates its result as a boolean.

Is that correct?

**Comment by substack** [comment]
Thanks for catching that. I've updated the readme with an accurate example.
